### ISSUE TITLE
App loses connection with speakers after some time

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.denon.heos#1]
From support:

> Wat de Denon Heos 1 betreft, dat probleem is nog aanwezig Homey verliest de koppeling met de Denon. Als je alles weer opnieuw opstart heb je kans dat de koppeling tussen Homey en Denon er weer is. Maar verliest daarna al snel weer de koppeling.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2587
