### ISSUE TITLE
[API] Handle 'command under process'

### ISSUE THREAD

**Issue by nlrb** [athombv/com.denon.heos#7]
When issuing a command (e.g. 'player/get_players') the HEOS CLI can respond with 'command under process', i.e. the response is not available yet.

The API should cater for this case and not return this result with undefined payload, but re-issue the request.

```
{ payload: undefined,
  command: 'player/get_players',
  message: { 'command under process': '' } }
```

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2582
